# Script PowerShell para criar local.properties no Windows
# Uso: .\scripts\criar-local-properties-windows.ps1

$ErrorActionPreference = "Continue"

Write-Host "🔧 Criando local.properties para Windows..." -ForegroundColor Cyan
Write-Host ""

# Verificar se já existe
if (Test-Path "local.properties") {
    Write-Host "⚠️  local.properties já existe!" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Conteúdo atual:" -ForegroundColor Cyan
    Get-Content local.properties
    Write-Host ""
    Write-Host "⚠️  Arquivo já existe. Será sobrescrito." -ForegroundColor Yellow
    Write-Host "💡 Se não quiser sobrescrever, cancele (Ctrl+C) e edite manualmente." -ForegroundColor Cyan
    Start-Sleep -Seconds 2
}

# Tentar encontrar Android SDK automaticamente
Write-Host "🔍 Procurando Android SDK..." -ForegroundColor Yellow

$sdkPaths = @(
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Android\Sdk",
    "$env:ANDROID_HOME",
    "$env:ANDROID_SDK_ROOT"
)

$sdkPath = $null
foreach ($path in $sdkPaths) {
    if ($path -and (Test-Path $path)) {
        $sdkPath = $path
        Write-Host "✅ Android SDK encontrado em: $sdkPath" -ForegroundColor Green
        break
    }
}

# Se não encontrou, usar caminho padrão ou pedir
if (-not $sdkPath) {
    Write-Host "❌ Android SDK não encontrado automaticamente." -ForegroundColor Red
    Write-Host ""
    Write-Host "💡 Como encontrar o caminho:" -ForegroundColor Cyan
    Write-Host "   1. Abra Android Studio" -ForegroundColor Gray
    Write-Host "   2. File → Settings → Appearance & Behavior → System Settings → Android SDK" -ForegroundColor Gray
    Write-Host "   3. Copie o caminho mostrado" -ForegroundColor Gray
    Write-Host ""
    Write-Host "📝 Caminhos comuns no Windows:" -ForegroundColor Yellow
    Write-Host "   - $env:LOCALAPPDATA\Android\Sdk" -ForegroundColor Gray
    Write-Host "   - $env:USERPROFILE\AppData\Local\Android\Sdk" -ForegroundColor Gray
    Write-Host ""
    
    # Tentar usar variável de ambiente
    if ($env:ANDROID_HOME) {
        $sdkPath = $env:ANDROID_HOME
        Write-Host "✅ Usando ANDROID_HOME: $sdkPath" -ForegroundColor Green
    } elseif ($env:ANDROID_SDK_ROOT) {
        $sdkPath = $env:ANDROID_SDK_ROOT
        Write-Host "✅ Usando ANDROID_SDK_ROOT: $sdkPath" -ForegroundColor Green
    } else {
        Write-Host "⚠️  Não foi possível detectar automaticamente." -ForegroundColor Yellow
        Write-Host "💡 Crie o arquivo local.properties manualmente com:" -ForegroundColor Cyan
        Write-Host "   sdk.dir=C:\\\\Users\\\\SeuUsuario\\\\AppData\\\\Local\\\\Android\\\\Sdk" -ForegroundColor Gray
        exit 1
    }
    
    # Validar caminho
    if (-not (Test-Path $sdkPath)) {
        Write-Host "❌ Caminho não encontrado: $sdkPath" -ForegroundColor Red
        Write-Host "💡 Crie o arquivo local.properties manualmente." -ForegroundColor Yellow
        exit 1
    }
}

# Converter caminho para formato do Gradle (escapar barras)
$sdkPathEscaped = $sdkPath -replace '\\', '\\'

# Criar arquivo
$content = @"
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=$sdkPathEscaped
"@

$content | Out-File -FilePath "local.properties" -Encoding UTF8

Write-Host ""
Write-Host "✅ local.properties criado com sucesso!" -ForegroundColor Green
Write-Host ""
Write-Host "📄 Conteúdo:" -ForegroundColor Cyan
Get-Content local.properties
Write-Host ""
Write-Host "🧪 Testando build (opcional)..." -ForegroundColor Yellow

# Testar se funciona (opcional, pode falhar se SDK não estiver completo)
if (Test-Path "gradlew.bat") {
    try {
        $testOutput = .\gradlew.bat compileDebugKotlin --console=plain 2>&1 | Out-String
        if ($testOutput -match "BUILD SUCCESS") {
            Write-Host "✅ Build passou! Tudo configurado corretamente!" -ForegroundColor Green
        } else {
            Write-Host "⚠️  Build ainda pode ter problemas." -ForegroundColor Yellow
            Write-Host "💡 Execute: .\scripts\diagnostico-build-local.ps1 para mais detalhes" -ForegroundColor Cyan
        }
    } catch {
        Write-Host "⚠️  Não foi possível testar o build automaticamente." -ForegroundColor Yellow
        Write-Host "💡 Teste manualmente com: .\gradlew.bat compileDebugKotlin" -ForegroundColor Cyan
    }
} else {
    Write-Host "⚠️  gradlew.bat não encontrado. Teste manualmente após configurar." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "✅ local.properties criado!" -ForegroundColor Green
Write-Host "💡 Próximo passo: Teste o build com .\gradlew.bat compileDebugKotlin" -ForegroundColor Cyan
Write-Host ""
