# Script PowerShell para criar local.properties no Windows
# Uso: .\scripts\criar-local-properties-windows.ps1

$ErrorActionPreference = "Continue"

Write-Host "🔧 Criando local.properties para Windows..." -ForegroundColor Cyan
Write-Host ""

# Verificar se já existe
if (Test-Path "local.properties") {
    Write-Host "⚠️  local.properties já existe!" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Conteúdo atual:" -ForegroundColor Cyan
    Get-Content local.properties
    Write-Host ""
    $sobrescrever = Read-Host "Deseja sobrescrever? (S/N)"
    if ($sobrescrever -ne "S" -and $sobrescrever -ne "s") {
        Write-Host "Operação cancelada." -ForegroundColor Yellow
        exit 0
    }
}

# Tentar encontrar Android SDK automaticamente
Write-Host "🔍 Procurando Android SDK..." -ForegroundColor Yellow

$sdkPaths = @(
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Android\Sdk",
    "$env:ANDROID_HOME",
    "$env:ANDROID_SDK_ROOT"
)

$sdkPath = $null
foreach ($path in $sdkPaths) {
    if ($path -and (Test-Path $path)) {
        $sdkPath = $path
        Write-Host "✅ Android SDK encontrado em: $sdkPath" -ForegroundColor Green
        break
    }
}

# Se não encontrou, pedir ao usuário
if (-not $sdkPath) {
    Write-Host "❌ Android SDK não encontrado automaticamente." -ForegroundColor Red
    Write-Host ""
    Write-Host "💡 Como encontrar o caminho:" -ForegroundColor Cyan
    Write-Host "   1. Abra Android Studio" -ForegroundColor Gray
    Write-Host "   2. File → Settings → Appearance & Behavior → System Settings → Android SDK" -ForegroundColor Gray
    Write-Host "   3. Copie o caminho mostrado" -ForegroundColor Gray
    Write-Host ""
    $sdkPath = Read-Host "Digite o caminho do Android SDK"
    
    # Validar caminho
    if (-not (Test-Path $sdkPath)) {
        Write-Host "❌ Caminho não encontrado: $sdkPath" -ForegroundColor Red
        Write-Host "💡 Verifique o caminho e tente novamente." -ForegroundColor Yellow
        exit 1
    }
}

# Converter caminho para formato do Gradle (escapar barras)
$sdkPathEscaped = $sdkPath -replace '\\', '\\'

# Criar arquivo
$content = @"
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=$sdkPathEscaped
"@

$content | Out-File -FilePath "local.properties" -Encoding UTF8 -NoNewline

Write-Host ""
Write-Host "✅ local.properties criado com sucesso!" -ForegroundColor Green
Write-Host ""
Write-Host "📄 Conteúdo:" -ForegroundColor Cyan
Get-Content local.properties
Write-Host ""
Write-Host "🧪 Testando build..." -ForegroundColor Yellow

# Testar se funciona
$testResult = .\gradlew.bat compileDebugKotlin --console=plain 2>&1 | Select-String -Pattern "BUILD SUCCESS|BUILD FAILED" | Select-Object -First 1

if ($testResult -match "BUILD SUCCESS") {
    Write-Host "✅ Build passou! Tudo configurado corretamente!" -ForegroundColor Green
} else {
    Write-Host "⚠️  Build ainda falhou. Verifique os erros acima." -ForegroundColor Yellow
    Write-Host "💡 Execute: .\scripts\diagnostico-build-local.ps1 para mais detalhes" -ForegroundColor Cyan
}

Write-Host ""
